# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemservico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_itemservico', models.CharField(default='', max_length=50, verbose_name='Descrição')),
                ('val_itemservico', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'itemservico',
                'verbose_name_plural': 'itensservicos',
                'ordering': ['desc_itemservico'],
            },
        ),
        migrations.CreateModel(
            name='servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_servico', models.CharField(default='', max_length=50, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'servico',
                'verbose_name_plural': 'servicos',
                'ordering': ['desc_servico'],
            },
        ),
        migrations.AddField(
            model_name='itemservico',
            name='servico',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='simulador.servico'),
        ),
    ]
