# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0002_itemservico_ind_selecionado'),
    ]

    operations = [
        migrations.CreateModel(
            name='imposto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_imposto', models.CharField(default='', max_length=50, verbose_name='Descrição')),
                ('val_imposto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('perc_imposto', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'imposto',
                'verbose_name_plural': 'impostos',
                'ordering': ['desc_imposto'],
            },
        ),
        migrations.AddField(
            model_name='itemservico',
            name='qtd_itemservico',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='itemservico',
            name='val_totalitemservico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemservico',
            name='val_itemservico',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
