# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0003_auto_20180508_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imposto',
            name='perc_imposto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='imposto',
            name='val_imposto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
