# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0004_auto_20180508_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imposto',
            name='val_imposto',
        ),
        migrations.AddField(
            model_name='imposto',
            name='val_outros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='itemservico',
            name='val_outros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='itemservico',
            name='val_recolhimentofundo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='imposto',
            name='perc_imposto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='itemservico',
            name='val_itemservico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='itemservico',
            name='val_totalitemservico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
